def build_report(verdict: str, noise_detail: str, vit_detail: str) -> str:
    return (
        f"Verdict: {verdict}. "
        f"Statistical signal: {noise_detail} "
        f"Neural signal: {vit_detail} "
        "This result is generated by combining sensor-noise residual analysis with transformer-based image forensics."
    )
